import { createTypes } from "reduxsauce";

export default createTypes(`
  FETCH_WORKSPACE_REQUEST
  FETCH_WORKSPACE_SUCCESS
  FETCH_WORKSPACE_FAILED

  CREATE_WORKSPACE_REQUEST
  CREATE_WORKSPACE_SUCCESS
  CREATE_WORKSPACE_FAILED

  GET_WORKSPACE_REQUEST
  GET_WORKSPACE_SUCCESS
  GET_WORKSPACE_FAILED
`);